export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const PASSWORD_RESET_EMAIL_SENT = 'PASSWORD_RESET_EMAIL_SENT'

// Saga types
export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START'
export const SIGN_UP_USER_START = 'SIGN_UP_USER_START'